name: house_price_pred
channels:
  - defaults
dependencies:
  - ca-certificates
  - libffi
  - openssl
  - pip
  - python
  - setuptools
  - sqlite
  - wheel
  - pip:
      - alembic
      - blinker
      - certifi
      - charset-normalizer
      - click
      - cloudpickle
      - colorama
      - contourpy
      - cycler
      - databricks-cli
      - docker
      - entrypoints
      - flask
      - fonttools
      - gitdb
      - gitpython
      - greenlet
      - idna
      - importlib-metadata
      - importlib-resources
      - itsdangerous
      - jinja2
      - joblib
      - kiwisolver
      - mako
      - markdown
      - markupsafe
      - matplotlib
      - mlflow
      - numpy
      - oauthlib
      - packaging
      - pandas
      - pillow
      - protobuf
      - pyarrow
      - pyjwt
      - pyparsing
      - python-dateutil
      - pytz
      - pyyaml
      - querystring-parser
      - requests
      - scikit-learn
      - scipy
      - six
      - smmap
      - sqlalchemy
      - sqlparse
      - tabulate
      - threadpoolctl
      - typing-extensions
      - tzdata
      - urllib3
      - waitress
      - websocket-client
      - werkzeug
      - xgboost
      - zipp
      - boto3